const bicycles = [
  {
    id: "jsgfasf",
    name: "Mountain Bike",
    img: "Images/Bikes/mountain.jpg",
    price: "$247500",
    recommendation: "Good for racing",
    desc: "Mountain bikes are most widely used bicycle type. It was designed for traversing forests and rougher or mountainous terrains. Its construction differs from a typical bicycle in many ways. <br/> The most noticeable of these differences are the inclusion of suspension on the frame and fork, larger knobby tires, more durable heavy-duty wheels, more powerful brakes, and lower gear ratios, which are needed for steep gradients better traction.",
  },
  {
    id: "jkjxhf",
    name: "Road Bike",
    img: "Images/Bikes/road.jpg",
    price: "$147500",
    recommendation: "Meant for riding on tarmac.",
    desc: "Road Bikes are the `<strong>most specialized of all types</strong>` of bikes and are meant for only riding on tarmac. The advantages of road bikes are speed, low weight, and an aerodynamic riding position. <br/> It allows you to ride for longer and see more. Typically,road bikes are more expensive compared to other types, but there are good cheaper models on market. They are not meant for racing but still offer you a ride full of pleasure and fun.",
  },
  {
    id: "jkj;lkj",
    name: "Hybrid Bike",
    img: "Images/Bikes/hybrid.jpg",
    price: "$44700",
    recommendation: "Best fo bicycle tours",
    desc: "Hybrid bikes are finding more and more supporters due to their being the most versatile bikes on the market. Without favoring one surface over another they allow for comfort and efficiency in forests and streets alike. Typically, a hybrid bike has 21 - 27 gears and 28' wheels, that are around 35mm wide.<br/>It is also possible to equip it with various accessories, making it nearly indispensable for bicycle tours. The larger wheel diameter is a definite advantage which allows for greater speeds and lowers rolling resistance.",
  },
  {
    id: "sly';skd",
    name: "City Bike",
    img: "Images/Bikes/city.jpg",
    price: "$4247500",
    recommendation: "Mainly designed for streets",
    desc: "City bikes roll much better on city streets and are usually fully equipped. That is, the standard equipment includes lights, a rare pack, a bicycle stand, fenders, and a chain guard. <br/> They are mainly designed for streets, but they wont disappoint you on hard-packed forest roads either. City bikes typically have between 1 and 27 gears. The price depends on the equipment and quality and ranges from $250 to several thousand dollars.",
  },
  {
    id: "ldfh",
    name: "Kid Bike",
    img: "Images/Bikes/kids.jpg",
    price: "$247500",
    recommendation: "Intended for children",
    desc: "Kids' Bikes' wheels range between 12' and 24'. Bicycle riding for kids could start at the age of two, usually on a 12' balance bike. Bigger tires can be used for 10-13-year-olds, and bikes with gears are usually offered from the age of five. <br/>High-quality and durable kids' bike can cost from around $100. Pedal-less Bikes (balance bikes) are great for kids' physique and usually cost even less. There are also high-end mountain and road bikes for kids, intended for children who love racing at a young age.",
  },
  {
    id: "qljdask",
    name: "Fixed Gear Bike",
    img: "Images/Bikes/fixed.jpg",
    price: "$37500",
    recommendation: "Good for bike messengers",
    desc: "Fixed and single gear bikes are built or rebuilt to be minimalistic as possible. A fixed-gear drivetrain has the drive sprocket (or cog) threaded or bolted directly to the hub of the back wheel, so that the rider cannot stop pedaling. When the rear wheel turns, the pedals turn in the same direction at the same pace.<br/>Most fixed gear bicycles only have a front brake, and some have no brakes at all. If those aspects dont bother you then they are very easy to ride on streets and lack parts that can break. they can be commonly seen among bike messengers in big cities because they force them to stay in flow with the traffic and reach their destination more quickly. Fixies can cost as little as several hundred dollars or as much as several dollars.",
  },
  {
    id: ";pocif",
    name: "Cruiser Bike",
    img: "Images/Bikes/cruiser.jpg",
    price: "$147500",
    recommendation: "For comfortable ride.",
    desc: "Cruiser bikes are focused on comfort, style, and affordability, compared to mountain and racing bikes which focus more on performance. They have a classic 'retro' look, reliable mechanical performance offers a comfortable ride, and come at a relatively low price.<br/>They usually cost less than $1000 and many are priced below $500.",
  },
  {
    id: "jmlfhb",
    name: "Tandem Bike",
    img: "Images/Bikes/tandem.webp",
    price: "$387500",
    recommendation: "Best for two riders.",
    desc: "The tandem bike concept is known to many, but these bikes are not too popular in the cycling world. That is because you need two people to ride one. The fact that you need a second person to ride one makes them appealing to many. Tandem bikes are a great way to spend time with your loved ones.<br/>Even though both cranksets are linked together with a chain and rotate at the same time, the two riders dont need to produce the same power. One rideer can do all the hard work, whereas the other can simply enjoy the ride. ",
  },
  {
    id: "uhxciuo",
    name: "Tricycles",
    img: "Images/Bikes/trikes.jpg",
    price: "$17500",
    recommendation: "Perfect for carrying loads",
    desc: "Trikes or tricycles, as you might guess from the name, are types of bikes with three wheels. They exist in the form of ordinary bikes, but they are also made as recumbents and cargo bikes. This bike design is perfect for carrying loads because there is a lot of room for cargo area in the back. <br/>Trikes are often popular among kids and among older folks who are not too confident in their riding skills. These bikes are also popular choice in industrial and warehouse applications because of their popularity.",
  },
  {
    id: "xbnskfjn",
    name: "Recumbent Bike",
    img: "Images/Bikes/recumbent.jpg",
    price: "$11500",
    recommendation: "Good for those suffering from back issues.",
    desc: "Recumbent bikes are very popular among older riders and those who are suffering from back issues. These types of bikes have a long and low design that almost puts the rider in a lying-down position. They have a seat with a brackrest, so the force on the back is not as strong as it is on a regular bike. They are also great for knee issues, because of the forward-pedaling motion, instead of a downward-pedaling one.<br/> Even though recumbent bicycles are more challenging to reide uphill, they are a popular choice among some world travelers because of how comfortable they are.",
  },
  {
    id: "ksdhg",
    name: "Cargo Bike",
    img: "Images/Bikes/cargo.jpg",
    price: "$71500",
    recommendation: "Can used to transport goods, pets and human.",
    desc: "Cargo bikes (also known as Freight bikes) are simple bicycles that have a cargo area at the front or the back of the bike. They can be used to transport goods,pets, and even kids and adults, depending on the size of the cargo area.<br/> The cargo area can be asimple platform, on which you can strap your load, or it can resemble a basket or a crate. These bikes are usually made of steel because it provides a sturdier construction. They typically have just one gear, but some might have more.",
  },
  {
    id: "skdhjd",
    name: "Fat Bike",
    img: "Images/Bikes/fat.jpg",
    price: "$51500",
    recommendation: "Suitable for riding in deep snow, mud and rocks.",
    desc: "Fatbikes are extremely popular today due to their pratically and their mean loks. They have big 26' tires which makes them suitable for riding in deep snow, mud, on rocks, and anywhere else where the ordinary MTB isnt good.<br/> Fatbikes are gaing popularity very quickly, as was the case with cyclocross bikes years ago. If you are planning a long tour off the beaten track, exploring the backcountry where it will be hard to find roads and trails, then a fat bike is a fantastic choice.",
  },
  {
    id: ".skjdvk",
    name: "Electric Bike",
    img: "Images/Bikes/electric.jpg",
    price: "$251500",
    recommendation: "Good for older people.",
    desc: "Electric bikes, also known as e-bikes or boosters, are bicycles with an integrated electric motor that can be used for assistance on the road. They retain the ability to be pedaled by the rider and are therefore not electric motorcycle.<br/> E-bikes use rechargeable batteries and the lighter varieties can go up to 16 - 20mph. Today, e-bikes come in the form of hybrid bikes, city bikes, cruisers, and even road bikes and mountain bikes. They are typically used by older people or those struggling with injuries.",
  },
  {
    id: "dskjhh",
    name: "BMX",
    img: "Images/Bikes/bmx.1.jpg",
    price: "$251500",
    recommendation: "Good for older people.",
    desc: " The term 'BMX' is the acronym for three words, bicycle (B), moto (M), and cross (X). BMX bikes are typically based around 20in wheels, although other wheel sizes can be found on race bikes. A BMX bike is an off-road sport bicycle used for racing or stunt riding. Simple in their build and operation, these bikes can handle certain loads and tackle demanding terrains that mountain bikes and road bikes would never dare to.<br/> BMX bikes are smaller than other bikes, and much stockier as well. They have a simple frame setup, and use thick, fat tires for better traction and shock absorption. Multiple gears are a rarity, and hand brakes are only utilized on certain types.",
  },
];
const accessories = [
  {
    id: "lsdfl",
    name: "Helmet",
    img: "Images/Accessories/helmet.avif",
    price: "$24",
    recommendation: "Head protection",
    desc: "Helmets protect the most importaant thing we have and without being too dramatic, weraing an approved, proper fitted helmet can be the difference between surving a crash or not. When looking for a helmet, there are some key considerations.<ul><li>Ventilation</li><li>Weight</li><li>Safety</li><li>Fit</li></ul>",
  },
  {
    id: "hdkks",
    name: "Shoe",
    img: "Images/Accessories/shoes.avif",
    price: "$44",
    recommendation: "Improves power transfer",
    desc: "As one of three contact points, a rider has to their bike, shoe are crucial to your comfort and performance. Road bike shoes are designed to be lightweight, and stiff to improve power transfer and have several widths and closing mechanisms to cater for individual needs.Below are some key considerations when choosing a bicycle shoe.<ul><li>Sizing</li><li>Shape</li><li>Cleats</li><li>Fastening mechanism</li><li>Ventilation</li></ul>",
  },
  {
    id: "lsdfl",
    name: "Sunglasses",
    img: "Images/Accessories/glasses.avif",
    price: "$21",
    recommendation: "Good for vision",
    desc: "Road-specific sunglasses are generally lightweight, with a mix of interchangable lenses and a large field of vision so as to not obstruct your view whether you are riding aggresively in the drops or sitting up climbing a mountain. Its always a good idea to check for a comfortable fit on your head and ensure the sunglasses fit with your helmet too",
  },
  {
    id: "opoduk",
    name: "Clothing",
    img: "Images/Accessories/clothing.avif",
    price: "$24",
    recommendation: "Good for breathability",
    desc: "Road cycling clothing is made to fit close to the body to improve aerodynamics and prevent chaffing. There are many different fabrics to choose from, and typically the more it costs, the better it is for weight, breathability, and comfort. Synthetic fabrics like polyester and elastane are commonly used to provide lightweight, strechable, wicking and highly durable clothing.",
  },
  {
    id: "isjdhk",
    name: "Lights",
    img: "Images/Accessories/lyts.avif",
    price: "$55",
    recommendation: "Best for riding in the dark",
    desc: "Riding with bike lights is no brainer, regardless of whether you predominantly ride during the day or in the dark. A Denmark-based study concluded that eight out of ten cycling accidents occur during the day, and the use of lights during the day is the number one thing cyclists can do to make themselves safer. We've highlighted the key features to keep an eye out for when choosing bicylce lights.<ul><li>Be seen or to see with</li><li>Road Rules</li><li>Lumen count</li><li>Mounting</li><li>Budget</li><li>Runtime and battery</li></ul>",
  },
  {
    id: "ajnd;",
    name: "Cycling Computer",
    img: "Images/Accessories/computers.avif",
    price: "$224",
    recommendation: "Raises performance",
    desc: "For many, purchasing a cycling-specific computer is the number one thing that will raise performance and output on the bike. A cycling computer allows you to track your performance in real time and over a long period, showing your improvement (hopefully).Cycling computers gives us a wealth of real time information, including necessary information such as speed, distance and the ride time. Whwn purchasing a cycling computer, look out for<ul><li>clear display thats easy to view</li><li>has a long battery life</li><li>easy to mount to the bike</li></ul> ",
  },
  {
    id: "ldjdkd",
    name: "Bottle Cages",
    img: "Images/Accessories/water.avif",
    price: "$8",
    recommendation: "For dehydration",
    desc: "Bottle cages might not spring to mind straight away, however, ride for over 30 minutes, and you will soon find them essential. One bottle cage is likely enough for those riding under two hours; however, you will want two on your bike for anything longer. Even if you are not big on a proper hydration a second bottle cage can be used to carry your spares in a canister. When selecting a bidon (cycling speak for a bottle), make sure it has :<ul><li>Enough capacity for your needs</li><li>Secure safety cap to prevent spillage</li><li>Removable top to easily clean and refill</li><li>Fits your bike</li></ul>",
  },
  {
    id: "l;sfsdfl",
    name: "Bells",
    img: "Images/Accessories/bells.avif",
    price: "$ 11",
    recommendation: "Creates awareness",
    desc: "Bells, like helmets, should (and in some states must) be a permanent accessory on road bikes. They are a small, inexpensive way of letting people know you are coming and much more acceptable than yelling at people to move to the left. When purchasing, look for bells that are: <ul><li>Easily mountable to a variety of bar diameters</li><li>Loud enough to be heard in traffic</li><li>With small footprint</li></ul>",
  },
  {
    id: "m,gl;sdk",
    name: "Saddle Bag and Storage",
    img: "Images/Accessories/saddle.jpg",
    price: "$44",
    recommendation: "Storage accessories",
    desc: "Storage on you bike is not as exciting as a new kit or pair of shoes but is an essential piece of equipment that will enhance your riding experience, especially when you ran into trouble. There are extensive list of things to pack for each ride, including tyre levers, two tubes, a hand pump or CO2 cartridges and a CO2 inflator. If you dont want to use a new tube each time, you can also add a patch kit. Below are some key points to consider when purchasing a saddle bag or other storage device.<ul><li>Space</li><li>Weight distribution</li><li>Installation</li></ul>",
  },
  {
    id: "sdkfgd",
    name: "Trainers",
    img: "Images/Accessories/trainer.jpg",
    price: "$8128",
    recommendation: "For specific training",
    desc: "Whwn we talk of trainers, we think of winter, cold wether, rain, wind... seeking refuge when the outside climate seems against us. However, they can also be a great way to perform specific training, and thanks to the latest round of smart, trainers, ride with friends in the virtual world. Below are some points to consider before u purchase an indoor trainer <ul><li>Type</li><li>Resistance types</li><li>Smart trainer features</li><li>Practical features</li></ul>",
  },
  {
    id: "khgjd",
    name: "Tyre Inflator",
    img: "Images/Accessories/tyre.jpg",
    price: "$51",
    recommendation: "For inflating tyres",
    desc: "Having ypur tyres adequately inflated is a fundamental element of riding aroad bike. Not having enough pressure in your tyre could lead to pinch flats, a spongy feeling when cornering and a decrease in performance. Conversely, pumping up your tyres above the manufactures maximum limit could result in an overall harsh ride feel with poor traction, or worst, your tyre could explode off the rim.",
  },
  {
    id: "fhgfk;l",
    name: "Maintenance Kit",
    img: "Images/Accessories/maintenance.avif",
    price: "$535",
    recommendation: "Maintenance",
    desc: "The list of potential maintenance items is long and can grow exponentially. If you're not keen on doing any of your own maintenance and would rather let a shop handle that, then all you need is a bottle of chain lube and some rags, we've listed a few essential items to consider.<ul><li>Chain lube</li><li>Degreaser</li><li>Allen or hex key set</li><li>Workstand</li><li>Torque wrench</li></ul>",
  },
];

