const homepage = [
  {
    id: "gshagdhg",
    img: "Images/p-3.jpg",
    name: ["Van Diesel", "BloodShot", "2020"],
    link: "https://www.youtube.com/watch?v=vOUVVDWdXbo&t=70s",
  },
  {
    id: "ajsdf",
    img: "Images/coming10.jpg",
    name: ["Guardian", "Of The", "Galaxy"],
    link: "https://www.youtube.com/watch?v=JqcncLPi9zw",
  },
  {
    id: "asndfh",
    img: "Images/m5.jpg",
    name: ["DC", "The", "Aquaman"],
    link: "https://www.youtube.com/watch?v=2wcj6SrX4zw",
  },
];


const comingMoviesData = [
  {
    id: "sahksh",
    img: "Images/m10.jpg",
    title: ["Underworld", "Blood Wars"],
    cateory: ["Action", "Horror", "Thriller"],
    rating: "7.3",
  },
  {
    id: "asdjkh",
    img: "Images/coming1.jpg",
    title: ["Johnny English", "Strikes Again"],
    cateory: ["Comedy", "Action", "Thriller"],
    rating: "6.1",
  },
  {
    id: "ssd,",
    img: "Images/coming5.jpg",
    title: ["DC", "Justice League"],
    cateory: ["Action", "Horror", "Thriller"],
    rating: "7.8",
  },
  {
    id: "askjaf",
    img: "Images/post-3.jpg",
    title: ["Disney", "Jungle Cruise"],
    cateory: ["Action", "Adventure", "Horror"],
    rating: "7.8",
  },
  {
    id: "dshfgs",
    img: "Images/post-9.jpg",
    title: ["Marvel", "WandaVision"],
    cateory: ["Action", "Sci-Fi", "Thriller"],
    rating: "7.5",
  },
  {
    id: "akdsf",
    img: "Images/post-4.jpg",
    title: ["Dune", "it Begins"],
    cateory: ["Action", "Adventure", "Thriller"],
    rating: "7.3",
  },
  {
    id: "lasdk",
    img: "Images/p-5.jpg",
    title: ["Marvel", "Proximamente"],
    cateory: ["Action", "Horror", "Thriller"],
    rating: "6.5",
  },
  {
    id: "sadn;;",
    img: "Images/m9.jpg",
    title: ["Mortal", "Engines"],
    cateory: ["Adventure", "Action", "Thriller"],
    rating: "7.7",
  },
  {
    id: "asdjl",
    img: "Images/coming8.jpg",
    title: ["Black", "Widow"],
    cateory: ["Action", "Sci-Fi", "Thriller"],
    rating: "8.3",
  },
  {
    id: "sadhv",
    img: "Images/post-6.jpg",
    title: ["No Time", "To Die"],
    cateory: ["Action", "Love", "Thriller"],
    rating: "7.6",
  },
  {
    id: "sad,m",
    img: "Images/m7.jpg",
    title: ["Thor", "Courage is Immortal"],
    cateory: ["Action", "Adventure", "Thriller"],
    rating: "7.2",
  },
  {
    id: "asdmasd",
    img: "Images/m8.png",
    title: ["Bumblebee", "Every Hero has a Beginning"],
    cateory: ["Action", "Sci-Fi", "Thriller"],
    rating: "7.0",
  },
  {
    id: "sad,sdm",
    img: "Images/coming2.jpg",
    title: ["WarCraft", "The Beginning"],
    cateory: ["Empire", "Love", "Thriller"],
    rating: "7.6",
  },
  {
    id: "sadhv",
    img: "Images/coming7.jpg",
    title: ["Captain", "Marvel"],
    cateory: ["Sci-Fi", "Action", "Adventure"],
    rating: "6.5",
  },
  {
    id: "sd'sd",
    img: "Images/coming3.jpg",
    title: ["The", "Rampage"],
    cateory: ["Action", "Adventure", "Thriller"],
    rating: "7.8",
  },
];